app:
  mqtt:
    url: tcp://localhost:1883
    username: ""
    password: ""
    inboundTopics:
      - devices/+/telemetry
      - devices/+/telemetry/+
    ackTopics:
      - devices/+/commands/ack
    qos: 1
